name: MinecraftREST
version: '1.0.1'
main: com.minecraftrest.api.MinecraftREST
api-version: '1.20'
authors: [aymond]
description: A RESTful API interface for Minecraft servers with secure JWT authentication, player management, and server control
website: https://github.com/aymond/hive.minecraftrest
commands: {} 